name: .Net
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: [ self-hosted, windows, X64, test-server ]
    timeout-minutes: 0
    steps:
    - name: Check out
      uses: actions/checkout@v3.5.0
    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
